all: memory1 memory2 memory3 memory4 memory5a memory5b memory6

memory1: memory1.c
	gcc memory1.c -o memory1.o
memory2: memory2.c
	gcc memory2.c -o memory2.o
memory3: memory3.c
	gcc memory3.c -o memory3.o
memory4: memory4.c
	gcc memory4.c -o memory4.o
memory5a: memory5a.c
	gcc memory5a.c -o memory5a.o
memory5b: memory5b.c
	gcc memory5b.c -o memory5b.o
memory6: memory6.c
	gcc memory6.c -o memory6.o
clean:
	rm -rf *.o 
